[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
adventure_engine = "9qbdCw4BAiyecsGd1oJ1EfnCgYbBMxuYeWr7tpZ3BqAt"
hero_core = "B4aW9eJbVnTrTTR9SYqVRodYt13TAQEmkhJ2JNMaVM7v"
dungeon_nft = "3qfE22hKoyPcDvtuYEAkCj9kuFHJVdXRkN6Qpp4UZhuw"
player_economy = "7wWA6dk96DR9g3NVSw5iQkHFCidK7DdV3V71Auv9bZMj"

[programs.localnet]
adventure-engine = "9qbdCw4BAiyecsGd1oJ1EfnCgYbBMxuYeWr7tpZ3BqAt"
hero-core = "B4aW9eJbVnTrTTR9SYqVRodYt13TAQEmkhJ2JNMaVM7v"
dungeon-nft = "3qfE22hKoyPcDvtuYEAkCj9kuFHJVdXRkN6Qpp4UZhuw"
player-economy = "7wWA6dk96DR9g3NVSw5iQkHFCidK7DdV3V71Auv9bZMj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/phantom.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-dungeon-config = "node scripts/init-dungeon-config.js"
seeded-mint = "node scripts/seeded-mint.js"
hero-dev = "node scripts/hero-dev.js"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
