[workspace]
members = [
    "programs/hero-core",
    "programs/dungeon-nft",
    "programs/adventure-engine",
    # "programs/player-economy"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
